// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "LLUPIS-17":return img`
............................................................cc.....
...........................................................ccc.....
...........................................................cdc.....
..........................................................ccdc.....
..........................................................cddcc....
.........................................................ccddbcc...
.........................................................cdddbcc...
........................................................ccdddbdc...
.......................................................ccdddbddc...
......................................................ccdddbbddbcc.
....................................................ccbbddbbdddbdc.
..................................................cccddbddddddbddc.
.................................................ccddddbdddddbdddcc
................................................cdddddbbddddddddbcc
ccc............................................cdddddbbddddddddbddc
cdcc..........................................cddddddbbddddddbbddcc
cddcc........................................cddddddddbbdddddddddc.
.cddcc.......................................cdddddddddbddddddddc..
.cdddcc......................................cdddddddddbdddddbbbccc
ccbdddc......................................cbdddddddbbddddddddddc
cdbbddcc.................ccccccc.............cbdddddbbbddddddddddcc
cddbbddc...............ccbbbbbbbcc............cdddddbbddddddddddcc.
ccdddddcc.............ccbbbbbbbbbcc...........cdddddbbddddddbbbbc..
.cddddddcc............cbbbbbbbbbbbc...........cddddddbdddddddbbbc..
.ccddddddcc...........cbbbbbbffbbbcc.........cbddddddbddddddddddc..
..cddddddbccccccc....c111bbbbffbbbbcc......cccddddddbbddddbbdddcc..
...cddddbbdddddddcc..f111bbbbbbbbbbbccc..ccddddddbbbbdddddddbbbc...
..cbbbddbbddddddddcccfbb11cbbbbbbbbbbbcccddddddddbbdddddbdddddc....
.cdddbbdbbbbdddddddddfbbbbcbbbbbbbbbbb6cdddddddddbdddddddbdddc.....
.ccdddddddbbbddddddddfbbfccbbbbbbbbbbb6cdddbbbbdbbddddddddbbbc.....
..ccddddddddbddddddddfbfdcbbbbbbbbbbb66bddbbbdbbbbddbddbdddbc......
....cddddddbbddddddddffddcbbbbbbbbbbb663bbbdddddddddbddbbdddc......
....cbbddddbbdbbbddddddddcbbbbbbbbbbb663bbbddbdddddddbddbbbcc......
....cddbbdddbbbbbddddddddcbbbbbbbbb66633ddbddbdddbbdddbddccc.......
....ccddddddddddbdddddddccbbbbbbbbb6633dddbddbbdddbbddcccc.........
.....ccdddddddddbbddbbddcbbbbbbbbbb663dddddddcbbdddbbc.............
......ccddddddddbbbbbbddc6bbbbbbbb666ddddddcccccccccc..............
.......ccbbbbdddddddbbbbc666bb6666663ddddddc.......................
.........cbbddddddddddbbc66666666663dddddddc.......................
.........cdddddbddddddbccd3666633ddddddddddc.......................
.........ccddbbbddbdddbccdd33333dddddddddddc.......................
..........cccccddbbddbb.ccddddddddddddddddddc......................
..............ccccccbb...ccdddddddddddddddddc......................
...................cc.....ccddddddddddddddddcc.....................
...........................ccddddddddddbbbbddcc....................
............................bbbdddddddbbbbbddccccccc...............
.............................bbbddddddbdddddddddddbcc..............
.............................ccccddddbccccddddddddbbc..............
............................c3333cdddc3333cddddddcccc..............
...........................cc33333cbcc33333cdddddcc................
...........................c3333333cc3333333cdcdbbc................
...........................c3c3c3c3cc3c3c3c3cdccbbc................
...........................c3c3c3cb.c3c3c3cbbdbccc.................
............................bcbccc...bcbcccdbbbcc..................
............................................bccc...................
............................................bc.....................
...................................................................
...................................................................
...................................................................
...................................................................
...................................................................
...................................................................
...................................................................
...................................................................
...................................................................
...................................................................
...................................................................
...................................................................
...................................................................
...................................................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
